remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme #
title: [KANNON]
description: [This is the hosting website for the zine KANNON.]

layout: page
title: "KANNON"
permalink: /https://github.com/Batburner/KANNON/blob/main/Words%20%26%20Shit%20From%20my%20Brain%20by%20Batburner
